name: Build Ztncui

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # 每天的 0 点执行
  workflow_dispatch:
      inputs:
        clean_cache:
          description: 'Clear caches'
          required: false
          type: boolean

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd ./ztncui-docker
          sh build_ztncui.sh
